# Generated by Django 5.2.5 on 2025-08-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('sofifa_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('player_url', models.URLField()),
                ('short_name', models.CharField(max_length=100)),
                ('long_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('club_name', models.CharField(max_length=100)),
                ('league_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('player_positions', models.CharField(max_length=50)),
                ('overall', models.IntegerField()),
                ('real_face', models.URLField()),
                ('potential', models.IntegerField()),
                ('value_eur', models.FloatField(null=True, blank=True)),
            ],
        ),
    ]
