# Generated by Django 5.2.5 on 2025-08-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='value_eur',
            field=models.FloatField(blank=True),
        ),
    ]
