# Generated by Django 5.2.5 on 2025-08-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_value_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='real_face_local',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
    ]
