# Generated by Django 5.2.5 on 2025-08-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_real_face_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='real_face_local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
